### ISSUE TITLE
After setup connection to local DBs fails

### ISSUE THREAD

**Issue by leschiffres** [getredash/setup#76]
I have set up locally a redash instance and I try to access my local postgres instances, but connection fails. However I can access these with the same credentials from my terminal. What do I need to do, to establish connection?

**Comment by justinclift** [comment]
You'll need a few things for that to work, and it's pretty much the same list for any data source. :smile:

1. You'll need to know the correct IP address (or dns domain name or similar) for connecting to the database
  * This can sometimes be a bit tricky if your database is running locally and only listening on (say) "localhost", which Docker containers can't easily reach

2. The data source (PostgreSQL in this instance) has to be actually listening on that IP address and not have anything blocking incoming connections from your source IP address
  * Default firewall settings can commonly need adjusting for this bit

3. If the data source has its own security & authentication mechanisms, these have to be configured to allow access
  * PostgreSQL uses a text file (`pg_hba.conf`) to configure which IP addresses it'll allow connections from.  Redash will generally give an error message with details about your source IP not being allowed when this is the problem.  Generally it's not too hard to fix.

... and I'm pretty sure there's one more thing that's obvious which is not coming immediately to mind though.  Hmmm, I probably need more coffee. :wink:

Anyway, the above 3 should get you started in resolving the problem.  If the connection is just timing out when it tries to connect, then it's probably either item 1 or 2 above.

**Comment by imtayyabhayat** [comment]
`root@space:/var/www/data/setup# source setup.sh

Redash installation script. :)

Docker and Docker Compose are already installed, so skipping that step.
** Creating /opt/redash directory structure for Redash **
** Creating Redash environment file **

Environment file already exists, reusing that one + and adding any missing (mandatory) values

** Creating Redash Docker compose file **
** Creating redash_make_default.sh script **

*********************
** Starting Redash **
*********************
** Initialising Redash database **
[+] Creating 2/0
 ✔ Container redash-postgres-1  Running                                                                                                                           0.0s 
 ✔ Container redash-redis-1     Running                                                                                                                           0.0s 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 481, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "postgres"`
